"""Brewfile generator for nix-station Application Service.

Reads common and host-specific App Catalog TOML files and generates
a Brewfile at ~/.config/nix-station/generated/Brewfile.

Only homebrew-cask and mas entries are written to the Brewfile.
system and manual entries are skipped (system is pre-installed;
manual entries print setup instructions instead).

Usage:
    nix run nixpkgs#python3 -- scripts/service/generate_brewfile.py <host-id>

Example:
    nix run nixpkgs#python3 -- scripts/service/generate_brewfile.py macos-desktop
"""

from __future__ import annotations

import sys
from pathlib import Path

# Resolve repo root relative to this script
REPO_ROOT = Path(__file__).parent.parent.parent
INSTANCE_DIR = Path.home() / ".config" / "nix-station"

sys.path.insert(0, str(REPO_ROOT / "scripts" / "validator"))
from app_catalog import AppCatalogValidationError, load, validate  # noqa: E402


def load_catalog(toml_path: Path) -> dict[str, dict]:
    """Load and validate a catalog TOML, returning the apps dict."""
    raw = load(toml_path)
    result = validate(raw, str(toml_path))
    return result["apps"]


def merge_catalogs(*catalogs: dict[str, dict]) -> dict[str, dict]:
    """Merge multiple catalogs. Later catalogs override earlier ones."""
    merged: dict[str, dict] = {}
    for catalog in catalogs:
        merged.update(catalog)
    return merged


def generate_brewfile(apps: dict[str, dict]) -> tuple[str, list[str]]:
    """Generate Brewfile content from the merged app catalog.

    Returns (brewfile_content, manual_instructions).
    """
    cask_lines: list[str] = []
    mas_lines: list[str] = []
    manual_entries: list[tuple[str, list[str]]] = []

    for app_id, entry in apps.items():
        install = entry["install"]
        if install == "homebrew-cask":
            cask_lines.append(f'cask "{entry["package"]}"')
        elif install == "mas":
            mas_lines.append(f'mas "{entry["package"]}", id: {entry["mas_id"]}')
        elif install == "manual":
            manual_entries.append((app_id, entry.get("manual_steps") or []))
        # system entries are silently skipped

    lines: list[str] = [
        "# Generated by nix-station. Do not edit manually.",
        "# Source: hosts/common/apps.toml + hosts/<host>/apps.toml",
        "# Regenerate: nix run nixpkgs#python3 -- scripts/service/generate_brewfile.py <host-id>",
        "",
    ]

    if mas_lines:
        lines.append('brew "mas"')
        lines.append("")

    if cask_lines:
        lines.extend(cask_lines)
        lines.append("")

    if mas_lines:
        lines.extend(mas_lines)
        lines.append("")

    manual_instructions: list[str] = []
    for app_id, steps in manual_entries:
        for step in steps:
            manual_instructions.append(f"  [{app_id}] {step}")

    return "\n".join(lines).rstrip() + "\n", manual_instructions


def main() -> None:
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <host-id>", file=sys.stderr)
        sys.exit(1)

    host_id = sys.argv[1]
    common_path = REPO_ROOT / "hosts" / "common" / "apps.toml"
    host_path = REPO_ROOT / "hosts" / host_id / "apps.toml"

    missing = [p for p in [common_path, host_path] if not p.exists()]
    if missing:
        for p in missing:
            print(f"Error: catalog not found: {p}", file=sys.stderr)
        sys.exit(1)

    try:
        common_apps = load_catalog(common_path)
        host_apps = load_catalog(host_path)
    except AppCatalogValidationError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    apps = merge_catalogs(common_apps, host_apps)
    content, manual_instructions = generate_brewfile(apps)

    output_dir = INSTANCE_DIR / "generated"
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / "Brewfile"
    output_path.write_text(content)

    print(f"Generated: {output_path}")
    print(
        f"  homebrew-cask: {sum(1 for e in apps.values() if e['install'] == 'homebrew-cask')}"
    )
    print(f"  mas:           {sum(1 for e in apps.values() if e['install'] == 'mas')}")

    if manual_instructions:
        print("\nManual setup required:")
        for instruction in manual_instructions:
            print(instruction)


if __name__ == "__main__":
    main()
