# ~/.config/nix-station/flake.nix
# Generated by nix-station Wizard. Do not edit manually.
# To update: run `nix-station wizard` again or edit instance.toml and profiles/.
{
  inputs = {
    nix-station.url = "github:hisuilab/nix-station";
    nixpkgs.follows = "nix-station/nixpkgs";
    nix-darwin.follows = "nix-station/nix-darwin";
    home-manager.follows = "nix-station/home-manager";
    nix-homebrew.follows = "nix-station/nix-homebrew";
  };

  outputs =
    { nix-station, ... }:
    let
      instance = builtins.fromTOML (builtins.readFile ./instance.toml);
    in
    {
      darwinConfigurations.${instance.hostname} = nix-station.lib.mkDarwinConfiguration {
        hostConfig = nix-station.lib.loadHostTemplate instance.host_id;
        hostId = instance.host_id;
        hostname = instance.hostname;
        userProfile = nix-station.lib.loadUserProfile {
          name = instance.profile;
          profilesDir = ./profiles;
        };
      };
    };
}
