# ========================================
# Powerlevel10k 設定ファイル
# ========================================
# 使用フォント: MesloLGS NF
# ※WSL2の場合はWindows側にフォントをインストール後ターミナル設定でフォント指定
# ========================================
# p10k configure で再設定可能
# ========================================

# Generated by Powerlevel10k configuration wizard on 2024-10-08 at 01:02 JST.
# Based on romkatv/powerlevel10k/config/p10k-rainbow.zsh, checksum 44011.
# Wizard options: nerdfont-v3 + powerline, small icons, rainbow, unicode, 24h time,
# round separators, round heads, round tails, 2 lines, disconnected, no frame, sparse,
# many icons, concise, instant_prompt=verbose.

# カラーマップ表示用コマンド:
#   for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}; done

# ============================================================
# Theme Select
# ============================================================
# cyberpunk / gruvbox
# 未設定なら cyberpunk をデフォルトに。設定済み (theme コマンド後) はそのまま保持。
typeset -g P10K_THEME="${P10K_THEME:-cyberpunk}"

# オプションの一時変更
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  # 設定リセット
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  # Zsh 5.1以上が必要
  [[ $ZSH_VERSION == (5.<1->*|<6->.*) ]] || return

  # 分割設定ファイルのディレクトリ (~/.p10k.d/ へ Nix が配置)
  local p10k_conf_dir="${HOME}/.p10k.d"

  source "${p10k_conf_dir}/01-palette.zsh"    || return
  source "${p10k_conf_dir}/02-elements.zsh"
  source "${p10k_conf_dir}/03-layout.zsh"
  source "${p10k_conf_dir}/04-prompt-core.zsh"
  source "${p10k_conf_dir}/05-segments.zsh"
  source "${p10k_conf_dir}/06-devtools.zsh"
  source "${p10k_conf_dir}/07-cloud.zsh"
  source "${p10k_conf_dir}/08-behavior.zsh"
  source "${p10k_conf_dir}/09-utils.zsh"

  # 設定再読込
  (( ! $+functions[p10k] )) || p10k reload
}

# p10k configure が上書きするファイル
typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
